In [2]:
## Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

* Yes, there is difference between list_ and array_list.
    * **list_** is a normal list that we use in python. It's data types is <class 'list'>.No new library is required for this.
    * **arrary_list** is an numpy array. It's data types is <class 'numpy.ndarray'>. We need to import numpy to use this.

In [4]:
type(array_list)

numpy.ndarray

In [5]:
type(list_)

list

# ------------------------------------------------------

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [6]:
for i in list_: print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
for i in array_list: print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# -----------------------------------------------

#### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)
#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

* Yes, the element in the array_list is changed to int data type.
* And there will be no changes in list_

In [9]:
array_list = np.array(object = list_, dtype = int)

In [10]:
for i in list_: print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
for i in array_list: print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# ------------------------------------------------

#### Consider the below code to answer further questions:

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
* (i) shape
* (ii) size

In [12]:
num_array.shape

(2, 3)

In [14]:
num_array.size

6

# -----------------------------------------------

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [21]:
test_array = np.zeros((3,3))
test_matrix = np.matrix(test_array)

In [18]:
test_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
test_matrix

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
test_matrix.shape

(3, 3)

In [24]:
test_matrix.size

9

# ----------------------------------------------------

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [26]:
np.matrix(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# --------------------------------------------------